<a href="https://colab.research.google.com/github/JonBen10/Module_14_Challenge/blob/main/GC_venture_funding_with_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data (2).csv

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    "applicants_data.csv", 
    parse_dates=True,
    infer_datetime_format=True  
)
# Review the DataFrame
applicant_data_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [ ]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])

# Review the DataFrame
applicant_data_df.head()

  APPLICATION_TYPE       AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10       Independent  ...    5000             1
1               T3       Independent  ...  108590             1
2               T5  CompanySponsored  ...    5000             0
3               T3  CompanySponsored  ...    6692             1
4               T3       Independent  ...  142590             1

[5 rows x 10 columns]

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [ ]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [ ]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [ ]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)
# Review the DataFrame
encoded_df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   APPLICATION_TYPE_T10  ...  SPECIAL_CONSIDERATIONS_Y
0                   1.0  ...                       0.0
1                   0.0  ...                       0.0
2                   0.0  ...                       0.0
3                   0.0  ...                       0.0
4                   0.0  ...                       0.0

[5 rows x 114 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [ ]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)
encoded_df = pd.concat(
    [numerical_variables_df, encoded_df], 
    axis="columns",
    sort=False
)
# Review the Dataframe
encoded_df.head()

   STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                       1.0                       0.0
1       1   108590  ...                       1.0                       0.0
2       1     5000  ...                       1.0                       0.0
3       1     6692  ...                       1.0                       0.0
4       1   142590  ...                       1.0                       0.0

[5 rows x 117 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [ ]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=[ "IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

   STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                       1.0                       0.0
1       1   108590  ...                       1.0                       0.0
2       1     5000  ...                       1.0                       0.0
3       1     6692  ...                       1.0                       0.0
4       1   142590  ...                       1.0                       0.0

[5 rows x 116 columns]

### Step 6: Split the features and target sets into training and testing datasets.

In [ ]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [ ]:
# Create a StandardScaler instance
X_scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = X_scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [ ]:
# Create the Sequential model instance
nn =  Sequential()

In [ ]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(1, activation="sigmoid"))

In [ ]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 58)                6786

 dense_7 (Dense)             (None, 29)                1711

 dense_8 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [ ]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5747 - accuracy: 0.7188
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7298
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7323
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7315
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7322
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7325
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7329
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7327
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7355
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7346
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7346
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7355
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7357
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7367
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7378
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7376
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7382
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7368
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7373
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7388
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7385
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7390
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7391
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7385
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7390
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7383
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7392
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7393
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7390
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7392
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7397
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7402
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7385
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7391
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7394
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7406
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7410
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7405
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7404
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7400
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7402

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [ ]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =  nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5552 - accuracy: 0.7317 - 317ms/epoch - 1ms/step
Loss: 0.5551559925079346, Accuracy: 0.7316617965698242

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [ ]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 4

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [ ]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [ ]:
# First hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))


# Output layer
nn.add(Dense(4, activation="sigmoid"))



# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 58)                6786

 dense_7 (Dense)             (None, 29)                1711

 dense_8 (Dense)             (None, 1)                 30

 dense_9 (Dense)             (None, 58)                116

 dense_10 (Dense)            (None, 4)                 236

=================================================================
Total params: 8,879
Trainable params: 8,879
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7402
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7410
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7414
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7415
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7410
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7421
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7417
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7411
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7423
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7414
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7418
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7406
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7415
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7408
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7410
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7420
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7414
Epoch 21/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5301 - accuracy: 0.7421
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7420
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7421
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7419
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7423
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7414
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7427
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7416
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7425
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7417
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7418
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7418
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7425
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7432
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7417
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7423
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7423
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7426
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7433
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7423
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7434
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7430
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7428
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7422
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7427
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7425
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7433
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7425

#### Alternative Model 2

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 6

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [ ]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [ ]:
# First hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Output layer
nn.add(Dense(4, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 58)                6786

 dense_7 (Dense)             (None, 29)                1711

 dense_8 (Dense)             (None, 1)                 30

 dense_9 (Dense)             (None, 58)                116

 dense_10 (Dense)            (None, 4)                 236

 dense_11 (Dense)            (None, 58)                290

 dense_12 (Dense)            (None, 4)                 236

=================================================================
Total params: 9,405
Trainable params: 9,405
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Fit the model
fit_model_A2 = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5247 - accuracy: 0.7436
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5255 - accuracy: 0.7439
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5249 - accuracy: 0.7446
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5245 - accuracy: 0.7441
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5247 - accuracy: 0.7445
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7432
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7441
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7441
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7441
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7442
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7445
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7442
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7439
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7444
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7441
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7446
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7441
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7448
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7438
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7443
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7442
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7442
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7443
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7444
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7439
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5258 - accuracy: 0.7448
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7440
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7442
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7440
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7439
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7441
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7443
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7445
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7446
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5242 - accuracy: 0.7441
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7440
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7443
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7438
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7440
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7443
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7444
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7448
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5238 - accuracy: 0.7446
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7444
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7444
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5235 - accuracy: 0.7443
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7440
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5242 - accuracy: 0.7443
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5243 - accuracy: 0.7445
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7441

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5744 - accuracy: 0.7297 - 330ms/epoch - 1ms/step
Loss: 0.5744152069091797, Accuracy: 0.72967928647995

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 7.8073 - accuracy: 1.1662e-04 - 312ms/epoch - 1ms/step
Loss: 7.807292461395264, Accuracy: 0.00011661807366181165

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 7.8073 - accuracy: 1.1662e-04 - 461ms/epoch - 2ms/step
Loss: 7.807292461395264, Accuracy: 0.00011661807366181165

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = "AlphabetSoup1.h5"

# Export your model to a HDF5 file
nn.save(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = "AlphabetSoup2.h5"

# Export your model to a HDF5 file
nn.save(file_path)